package org.arctix.security.hmac;

/**
 * Represents one-time password generated by OTP Engine.
 * 
 * @author aprasa2
 *
 */
public class OTP {

	String password;
	String hmac;

	public OTP(String pass, String hmac) {
		this.password = pass;
		this.hmac = hmac;
	}

	public String getPassword() {
		return password;
	}

	public String getHmac() {
		return hmac;
	}

}
